# zsh config
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="scenic"
plugins=(chruby git gitfast osx wd sudo brew bundler title-tab)

# load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# aliases 
source $HOME/.aliases

# zsh completion
autoload -U compinit
compinit

# zsh options
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS
# ironically the below setting would disable completion for aliases
# setopt COMPLETE_ALIASES 

# local config
[[ -a ~/.localrc ]] && source ~/.localrc

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
